### ISSUE TITLE
Confusing name

### ISSUE THREAD

**Issue by powerjg** [afarooqui98/ECS193a#100]
https://github.com/afarooqui98/ECS193a/blob/9e519421b4996fba42aefa4240a1d78b60bc8af2/m5_calls.py#L253

**Comment by powerjg** [comment]
# JASON: you've got to come up with better names.
    #        Also, you can't use duck-typing like this. You shouldn't ever
    #        change the type from a class to an instance.
    #        I suggest the following names `sim_object_cls` and `sim_object`

**Comment by afarooqui98** [comment]
see pr #109
