### ISSUE TITLE
getenv gem5_path doesn't work in all cases

### ISSUE THREAD

**Issue by powerjg** [afarooqui98/ECS193a#101]
https://github.com/afarooqui98/ECS193a/blob/9e519421b4996fba42aefa4240a1d78b60bc8af2/m5_calls.py#L6

This doesn't work for me. I think you should allow the user to specify GEM5_PATH=... on the command line/environment.

For instance, my directory structure looks like the following:
```
gem5/
  gem5-gui/
  gem5/
    build/
      gem5.opt
  gem5art/
  ...
```

Then, I try to run the GUI from the `gem5-gui/` directory as the following.

```
../gem5/build/X86/gem5.opt gui.py
```

To get that to work, I have to modify the code.

I think the following should work instead.

```
GEM5_HOME=../gem5 ../gem5/build/X86/gem5.opt gui.py
```

**Comment by rohitdhamankar** [comment]
i'll look into testing and implementing these changes
