### ISSUE TITLE
What is SymObject.parameters?

### ISSUE THREAD

**Issue by powerjg** [afarooqui98/ECS193a#102]
https://github.com/afarooqui98/ECS193a/blob/9e519421b4996fba42aefa4240a1d78b60bc8af2/m5_calls.py#L96

I can't figure out where this member (`object.parameters`) gets set. It's not in `sym_object.py`

What's the difference between `parameters` and the `SimObject.enumerateParams()`?

I think these (related) variables need more descriptive names.

**Comment by afarooqui98** [comment]
see pr #109
