### ISSUE TITLE
Ports are not connected when loading a ui file

### ISSUE THREAD

**Issue by powerjg** [afarooqui98/ECS193a#105]
If you save a file that has port wires, then close the GUI, then load the file it looks like there are wires connected, but when you press "instantiate" the wires aren't there.

**Comment by Ravishdeep10** [comment]
Yeah we found a formatting bug when loading in the values for the ports and seemed to have fixed it. Will be updated in the next merge to master.

**Comment by afarooqui98** [comment]
fixed in pr #109
