### ISSUE TITLE
ERROR: No Module named 'dialogs'

### ISSUE THREAD

**Issue by msubglb** [afarooqui98/ECS193a#168]
I am trying to run gem5_GUI with the following command.

**$GEM5_HOME/build/X86/gem5.opt gui.py**

But, see an error message: No Module named 'dialogs.

This module is installed and >python -c "import dialogs" works fine from the commandline. 

Appreciate any insights about what may be the issue.

Thanks

**Comment by msubglb** [comment]
pip3 install Dialogs
solved the issue.

**Comment by msubglb** [comment]
pip3 install Dialogs
solved the issue.

**Comment by m1chaelyeung** [comment]
it is not correct
