### ISSUE TITLE
Shouldn't automatically write json file on import

### ISSUE THREAD

**Issue by powerjg** [afarooqui98/ECS193a#44]
https://github.com/afarooqui98/ECS193a/blob/abfa3734bea2ec77b5236eec253394322ab53161/m5_calls/get_catalog.py#L39

This means that whenever the file is imported you'll write out a json file. These lines should be removed or wrapped in`__name__=="__main__"`

**Comment by Ravishdeep10** [comment]
This is a leftover from when we had to do the "hacky" way of running gem5. We got rid of the m5_calls directory and instead just use the script m5_calls.py to handle anything related to gem5.
